const Homeproduct =
    [
        {
            id: 1,
            Name: 'product1',
            price: "389",
            image: 'image/p1.jpeg',
            cat: 'piano',
            type: 'new',
        },
        {
            id: 2,
            Name: 'product2',
            price: '96',
            image: 'image/p2.jpeg',
            cat: 'piano',
            type: 'new',
        },
        {
            id: 3,
            Name: 'product3',
            price: '236',
            image: 'image/p3.jpeg',
            cat: 'piano',
            type: 'new',
        },
        {
            id: 4,
            Name: 'product4',
            price: '636',
            image: 'image/p4.jpeg',
            cat: 'piano',
            type: 'new',
        },
        {
            id: 5,
            Name: 'product5',
            price: '98',
            image: 'image/p5.jpeg',
            cat: 'piano',
            type: 'featured',
        },
        {
            id: 6,
            Name: 'product6',
            price: '59',
            image: 'image/p6.jpeg',
            cat: 'guitar',
            type: 'featured',
        },
        {
            id: 7,
            Name: 'product7',
            price: '956',
            image: 'image/p7.jpeg',
            cat: 'guitar',
            type: 'featured',
        },
        {
            id: 8,
            Name: 'product8',
            price: '389',
            image: 'image/p8.jpeg',
            cat: 'guitar',
            type: 'featured',
        },
        {
            id: 9,
            Name: 'product9',
            price: '67',
            image: 'image/p9.jpeg',
            cat: 'guitar',
            type: 'top',
        },
        {
            id: 10,
            Name: 'product10',
            price: '76',
            image: 'image/p10.jpeg',
            cat: 'drum',
            type: 'top',
        },
        {
            id: 11,
            Name: 'product11',
            price: '87',
            image: 'image/p11.jpeg',
            cat: 'drum',
            type: 'top',
        },
        {
            id: 12,
            Name: 'product12',
            price: '807',
            image: 'image/p12.jpeg',
            cat: 'drum',
            type: 'top',
        },
    ]
export default Homeproduct